import { GeneratedProject } from "../types";

export function generateConfigs(projectName: string): GeneratedProject {
  return [
    {
      path: 'package.json',
      content: JSON.stringify({
        name: projectName,
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
        },
        dependencies: {
          'next': 'latest',
          'react': 'latest',
          'react-dom': 'latest',
          '@supabase/supabase-js': 'latest',
        },
        devDependencies: {
          'typescript': 'latest',
          '@types/node': 'latest',
          '@types/react': 'latest',
          '@types/react-dom': 'latest',
        }
      }, null, 2)
    },
    {
      path: 'tsconfig.json',
      content: JSON.stringify({
        compilerOptions: {
          target: 'es5',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./src/*'] }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
      }, null, 2)
    },
    {
      path: 'next.config.ts',
      content: `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;`
    },
    {
      path: 'README.md',
      content: `# ${projectName}\n\nGenerated by RouteForge.`
    }
  ];
}
